name: bigeyebrow
favicon: null
layout_spectrum: 0.51724
typography_spectrum: 0.973577439552173
title: By Anil Nataly
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c2f43'
    - '#555763'
    - '#798988'
    - '#f3f5e0'
    - '#cdb89d'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
