name: bigeyebrow
favicon: null
layout_spectrum: 0.47682
typography_spectrum: 0.46885
title: i like bacon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c2f43'
    - '#555763'
    - '#798988'
    - '#f3f5e0'
    - '#cdb89d'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
